### ISSUE TITLE
LOAD VERY FEW RESULTS!!!

### ISSUE THREAD

**Issue by kenpokas** [hazelbag/iTunes-Media-Search#1]
hello My friend!!!what amazinggggggggggggggggg web and designnnnn....manyyyyyyyyy congratulations.but please can you make it increase unlimited results?I am searching for months one web with unlimited results!!!!!!!!!!!!pleaseeeeeeeee it would be greatttttttttttt dude!!!Happy Holidays

**Comment by hazelbag** [comment]
Hey there, thank for the feedback, are you running it in Heroku or on your local drive? If locally you can change the value in the backend to show all results. If on Heroku I will upload the new version shortly.

**Comment by kenpokas** [comment]
heyyyyyyyyy God bless you dude where answer me!!!My friend I dont knowwwww...I am not programmer unfortunatellyyyyyyyyyyy :( :( :( pleaseeeeeee mannnnnnnn could you make your amazingggggggggggggggggg web increase unlimited songs????say yessssssss pleaseeeeeeee!!!I am beggingggggggggggggg you!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hazelbag** [comment]
I will deploy it shortly allowing more search items

**Comment by kenpokas** [comment]
woowwwwwwwwwwww...please not more my friendddddd....but unlimited...pleaseeeeeeeee can you make it today????forgive my pacience but I am searching for months one web where increase unlimited results!!!!!!!!!!!!!pleaseeeeeeeee man!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hazelbag** [comment]
I will check what the API has to offer for unlimited, I will however remove the limited qty I added to the API and upload to Heroku, give me about an hour and it will be uploaded.

**Comment by kenpokas** [comment]
my frienddddddddddddddddd I have no wordssssssssssssssssssssssssssssss....God bless you one more timeeeeeeee!!!thanksssssssssssssss so so so muchhhhhhhhhhh!!!!do you have Facebook?

**Comment by hazelbag** [comment]
https://itunes-search-api-express.herokuapp.com/ I changed the limit but it will only give what the API allows.

**Comment by kenpokas** [comment]
my friend I know....itunes give just 200 results!!!but if someone is programmer I am sure can make it increase unlimited results!!!I am sure about it!!!pleaseeeeeee take a look!!!

**Comment by kenpokas** [comment]
my friend I know....itunes give just 200 results!!!but if someone is programmer I am sure can make it increase unlimited results!!!I am sure about it!!!pleaseeeeeee take a look!!!
